image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - package
  - deploy

before_script:
  - echo "Running CI/CD pipeline for Spring Boot Gym HTML App"

build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn --batch-mode clean compile
  only:
    - main

test:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn --batch-mode test
  only:
    - main

package:
  stage: package
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn --batch-mode package
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker build -t gym-app .
    - docker run -d -p 8080:8080 --name gym-app gym-app
    - echo "Waiting for app to start..."
    - for i in {1..30}; do
        curl --fail http://localhost:8080 && echo "App is up!" && break || sleep 2;
      done || (echo "App failed to start" && docker logs gym-app && exit 1)
  only:
    - main
