image: maven:3.9.4-eclipse-temurin-17

stages:
  - build
  - test
  - package
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

before_script:
  - echo "Running CI/CD pipeline for Spring Boot Gym HTML App"

cache:
  key: maven-cache
  paths:
    - /root/.m2/repository/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS dependency:go-offline
    - mvn $MAVEN_CLI_OPTS clean compile
  only:
    - main

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:
    - main

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Starting Spring Boot app in test mode..."
    - mvn $MAVEN_CLI_OPTS spring-boot:start > app.log 2>&1 &
    - echo "Waiting for app to start..."
    - for i in {1..30}; do
        curl --fail http://localhost:8080 && echo "App is up!" && break || sleep 2;
      done || (echo "App failed to start" && cat app.log && exit 1)
    - echo "App started successfully"
    - mvn $MAVEN_CLI_OPTS spring-boot:stop
  only:
    - main
