image: maven:3.9.4-eclipse-temurin-17

stages:
  - build
  - test
  - package
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

before_script:
  - echo "Running CI/CD pipeline for Spring Boot Gym HTML App"

cache:
  key: maven-cache
  paths:
    - /root/.m2/repository/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS dependency:go-offline
    - mvn $MAVEN_CLI_OPTS clean compile
  only:
    - main

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  only:
    - main

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Starting deployment..."
    - java -jar target/*.jar &
    - sleep 10
    - curl --fail http://localhost:8080 || (echo "Deployment failed" && exit 1)
  only:
    - main
