name: Build and Run Spring Boot App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      JAVA_HOME: 'C:\\Program Files\\Java\\jdk-17'
      PATH: 'C:\\Program Files\\Java\\jdk-17\\bin;${{ env.PATH }}'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
        shell: cmd

      - name: Run Spring Boot App
        run: java -jar target\\springboot-gym-html-app-1.0.0.jar
        shell: cmd

    # GitHub Actions doesn't have post steps like Jenkins,
    # so handle messages within the step results
