correct it 
how to run and deploy port number 8082
unable to run localhost:8082

name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test

    - name: Package App
      run: mvn package

    - name: Archive JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-gym-html-app
        path: target/*.jar
    - name: Build Docker image
      run: docker build -t your-dockerhub-username/gym-html-app .

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push your-dockerhub-username/gym-html-app
