name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build
      run: mvn clean install

    - name: Test
      run: mvn test

    - name: Package
      run: mvn package

    - name: Build Docker Image
      run: docker build -t sakshivirhajobsearch/gym-html-app .

    - name: Login to DockerHub
      run: echo "Job123Job#" | docker login -u "sakshivirhajobsearch" --password-stdin

    - name: Push Docker Image
      run: docker push sakshivirhajobsearch/gym-html-app

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull sakshivirhajobsearch/gym-html-app
          docker stop gym-html-app || true
          docker rm gym-html-app || true
          docker run -d -p 80:80 --name gym-html-app sakshivirhajobsearch/gym-html-app
